### ISSUE TITLE
Configure RSS limit under services key

### ISSUE THREAD

**Issue by jmooring** [frjo/hugo-theme-zen#129]
In the site config for the example site, change this:

```yaml
rssLimit: 20
```

To this:

```yaml
services:
  rss:
    limit: 20
```

The former obviously works, but is not documented and may be removed at some point.

<https://gohugo.io/configuration/services/#rsslimit>
