### ISSUE TITLE
Add menu entries to example site

### ISSUE THREAD

**Issue by jmooring** [frjo/hugo-theme-zen#130]
Just a suggestion to avoid stuff like this:
<https://discourse.gohugo.io/t/issues-with-installing-zen-theme/54184/>

Something like:

```yaml
menus:
  main:
    - name: Home
      pageRef: /
      weight: 10
    - name: Documentation
      pageRef: /documentation
      weight: 20
    - name: About
      pageRef: /about
      weight: 30
    - name: Contact
      pageRef: /contact
      weight: 40
    - name: Search
      pageRef: /search
      weight: 50
```
