### ISSUE TITLE
No podcast tags on rss despite of parameters exist

### ISSUE THREAD

**Issue by k0a8t1o6** [frjo/hugo-theme-zen#44]
RSS file generated from the rss link on the footer does not contain podcast tags for iTunes.
No example given on the exampleSite, so unsure if my implementation is correct.

The config.yaml is
```
params:
  contact: ...
  ...
  podcast:
    title: ...
    descriptions: ...
    ...
```

And each entry contains below as its markdown header
```
author: ...
title: ...
podcast: ...
  mp3: ...
  duration: ...
  image:
    src: ...
```
