### ISSUE TITLE
languageCode: "sv-SE" not changing the texts

### ISSUE THREAD

**Issue by mortenkjarulff** [frjo/hugo-theme-zen#48]
Hi,

My config.yaml:

```
baseurl: "https://gitte.one/"
title: "Gitte Kjærulff Møller"
theme: "zen"
languageCode: "sv-SE"

params:
  feedlinks: true
  podcast:
    title: "Gitte Kjærulff Møller"
    description: "Lydbøger."
    image: "images/podcast.jpg"
    category:
      name: "Books"
```

https://gitte.one/
The "Home" at the top and "Follow" is still English?

I can see that the language tag in the feeds has changed:
https://gitte.one/index.xml
https://gitte.one/podcast/index.xml
So something is in fact working.

What am I doing wrong?

/Morten
