### ISSUE TITLE
Different Zen theme settings for each language

### ISSUE THREAD

**Issue by arky** [frjo/hugo-theme-zen#73]
Is it possible to provide params for each language in a multilingual site. Am following the new config structure provide by [HUGO Docs project](https://github.com/gohugoio/hugoDocs/tree/master/config/_default)

Am declaring Zen theme params in `config/_default/params.toml`

``` toml 
[en]
contact = "ACME"
copyright = "© ACME 2023"
description = "ACME Project"

[de]
contact = "ACME"
copyright = " © ACME 2023"
description = "ACME Projekt"


```
